apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service #portfolio-app-service
spec:
  type: {{.Values.service.type}} #NodePort
  selector:
    app: portfolio
  ports:
    - port: {{.Values.service.port}} #80
      targetPort: {{.Values.service.targetPort}} #8080